<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Partes_CuerpoRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class Partes_CuerpoRepository extends EntityRepository
{
}
