<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Rasgos_DistRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class Rasgos_DistRepository extends EntityRepository
{
}
