<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Tipo_OrganizacionRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class Tipo_OrganizacionRepository extends EntityRepository
{
}
